### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by CloudsLetter** [koiNoCirculation/AEMobileApp#1]
您好，能否自定义44444端口与http/https协议而不是在代码中写死
物品总览页的icon一直为加载中icon，以及物品详情页中不会展示icon以及物品名称显示为undefined，使用仓库最新代码构建
另外可否提供一份itempanel.csv副本

**Comment by koiNoCirculation** [comment]
最新版已修复全部为加载中问题。
现在端口已经可以自定义了。
